name: Library-CI

on:
  push:
    branches: [master]
    paths:
      - "aplicacao/**"
  pull_request:
    branches: [master]
    paths:
      - "aplicacao/**"

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: docker-compose up -d app
        env:
          DB_HOST: localhost
      - name: Create db
        run: docker-compose run app rake db:create
      - name: Make migrations
        run: docker-compose run app rake db:migrate
      - name: Run tests
        run: docker-compose run app rake test
      - name: Upload code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: ./app/coverage/.resultset.json
