name: Library-CD

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: viniciussaturnino/Trabalho-Individual-2021-2/.github/workflows/library-ci.yml@main
  deploy:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: viniciussaturnino/library-gces
          context: "{{defaultContext}}:aplicacao"
